---
- name: VERIFY DEVICE HEALTH BY ANALYZING DIFFERENT PROCESSES
  hosts: routers
  gather_facts: false
  connection: network_cli


  tasks:
    - name: SHOW VERSION OF IOS SOFTWARE
      ios_command:
        commands:
          - show version
      register: config

    - name: SAVE OUTPUT TO ./devicehealth/
      copy:
       content: "{{ config.stdout[0] }}"
       dest: "{{ inventory_hostname }}_version.txt"
