---
- name: AUTOMATIC VPN RECONNECTION
  hosts: router1
  vars:
    address: "172.16.0.2"
  
  gather_facts: false
  connection: network_cli

  tasks:
    - name: SET NEW IPSEC ISAKMP ADDRESS
      ios_config:
        lines:
          - crypto isakmp key cisco address {{address}}
      
    - name: SET NEW PEER ADDRESS
      ios_config:
        lines:
          - set peer {{address}}
        parents: crypto map Crypt 10 ipsec-isakmp